// <auto-generated />
using System;
using KhoaLuan.Data.EF;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace KhoaLuan.Data.Migrations
{
    [DbContext(typeof(EnterpriseDbContext))]
    [Migration("20210518041224_UnitRecipes2")]
    partial class UnitRecipes2
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("KhoaLuan.Data.Entities.AppRole", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles");

                    b.HasData(
                        new
                        {
                            Id = new Guid("88a28f0b-99cd-4893-ab70-0189c8c7fec5"),
                            ConcurrencyStamp = "d0b68089-2370-4d74-bc70-b51f5ac129ba",
                            Description = "Vai trò Administrator",
                            Name = "Admin",
                            NormalizedName = "Admin"
                        });
                });

            modelBuilder.Entity("KhoaLuan.Data.Entities.AppUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<bool>("AccountType")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<DateTime>("BirthDay")
                        .HasColumnType("datetime2");

                    b.Property<string>("Card")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("Gender")
                        .HasColumnType("bit");

                    b.Property<int>("JobStatus")
                        .HasColumnType("int");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PathImage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers");

                    b.HasData(
                        new
                        {
                            Id = new Guid("0275d5a7-da4a-41c3-85ed-15e53cd1b7a0"),
                            AccessFailedCount = 0,
                            AccountType = true,
                            Address = "Cần Thơ",
                            BirthDay = new DateTime(2020, 1, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Card = "0123456789",
                            Code = "Admin",
                            ConcurrencyStamp = "343ecfd9-347d-4874-b037-bc1b9febb09c",
                            Email = "khoaluan@gmail.com",
                            EmailConfirmed = true,
                            FirstName = "Nam",
                            Gender = true,
                            JobStatus = 1,
                            LastName = "Lương Nhựt",
                            LockoutEnabled = false,
                            NormalizedEmail = "khoaluan@gmail.com",
                            NormalizedUserName = "admin",
                            PasswordHash = "AQAAAAEAACcQAAAAEIpakQ6bNTc9lLaoT1HSZjz6NHsKghVQfFAuZgZG95izUBhmcwL9JaHHVsw9kLZO0A==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "",
                            TwoFactorEnabled = false,
                            UserName = "admin"
                        });
                });

            modelBuilder.Entity("KhoaLuan.Data.Entities.Bill", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .UseIdentityColumn();

                    b.Property<decimal>("AmountPaid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18,2)")
                        .HasDefaultValue(0m);

                    b.Property<string>("CodeBill")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("ConvertNumbers")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValue(new DateTime(2021, 5, 18, 11, 12, 21, 540, DateTimeKind.Local).AddTicks(4339));

                    b.Property<Guid>("IdCreator")
                        .HasColumnType("uniqueidentifier");

                    b.Property<long>("IdPlan")
                        .HasColumnType("bigint");

                    b.Property<int>("IdSupplier")
                        .HasColumnType("int");

                    b.Property<string>("Images")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PaymentStatus")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<DateTime>("PurchaseDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValue(new DateTime(2021, 5, 18, 11, 12, 21, 541, DateTimeKind.Local).AddTicks(8583));

                    b.Property<string>("StorageCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int?>("Tax")
                        .HasColumnType("int");

                    b.Property<decimal>("TotalMoney")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18,2)")
                        .HasDefaultValue(0m);

                    b.HasKey("Id");

                    b.HasIndex("IdCreator");

                    b.HasIndex("IdPlan");

                    b.HasIndex("IdSupplier");

                    b.ToTable("Bills");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            AmountPaid = 50000m,
                            CodeBill = "01",
                            CreatedDate = new DateTime(2021, 5, 18, 11, 12, 21, 637, DateTimeKind.Local).AddTicks(7636),
                            IdCreator = new Guid("0275d5a7-da4a-41c3-85ed-15e53cd1b7a0"),
                            IdPlan = 1L,
                            IdSupplier = 1,
                            PaymentStatus = 1,
                            PurchaseDate = new DateTime(2021, 5, 18, 11, 12, 21, 637, DateTimeKind.Local).AddTicks(6374),
                            StorageCode = "AP1",
                            TotalMoney = 0m
                        });
                });

            modelBuilder.Entity("KhoaLuan.Data.Entities.BillDetail", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .UseIdentityColumn();

                    b.Property<int>("Amount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1);

                    b.Property<int?>("Discount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<long>("IdBill")
                        .HasColumnType("bigint");

                    b.Property<int>("IdMaterials")
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TotalPrice")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18,2)")
                        .HasDefaultValue(0m);

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("IdBill");

                    b.HasIndex("IdMaterials");

                    b.ToTable("BillDetails");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Amount = 2,
                            IdBill = 1L,
                            IdMaterials = 1,
                            Price = 30000m,
                            TotalPrice = 0m,
                            Unit = "kg"
                        },
                        new
                        {
                            Id = 2L,
                            Amount = 3,
                            IdBill = 1L,
                            IdMaterials = 1,
                            Price = 20000m,
                            TotalPrice = 0m,
                            Unit = "Trái"
                        });
                });

            modelBuilder.Entity("KhoaLuan.Data.Entities.ManageCode", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<long>("Location")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasDefaultValue(0L);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<bool>("Top")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<int>("TypeCode")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("ManageCodes");
                });

            modelBuilder.Entity("KhoaLuan.Data.Entities.Material", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<long>("Amount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasDefaultValue(0L);

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("IdMaterialsType")
                        .HasColumnType("int");

                    b.Property<string>("Image")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("Max")
                        .HasColumnType("bigint");

                    b.Property<long?>("Min")
                        .HasColumnType("bigint");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .UseCollation("SQL_Latin1_General_CP1_CI_AI");

                    b.Property<bool>("Reminder")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<DateTime>("ReminderEndDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValue(new DateTime(2021, 5, 18, 11, 12, 21, 580, DateTimeKind.Local).AddTicks(1987));

                    b.Property<DateTime>("ReminderStartDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValue(new DateTime(2021, 5, 18, 11, 12, 21, 580, DateTimeKind.Local).AddTicks(1575));

                    b.HasKey("Id");

                    b.HasIndex("IdMaterialsType");

                    b.ToTable("Materials");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Amount = 10L,
                            Code = "NVL1",
                            Description = "Bột gạo dùng để làm bánh",
                            IdMaterialsType = 1,
                            Max = 100L,
                            Min = 1L,
                            Name = "Bột gạo",
                            Reminder = false,
                            ReminderEndDate = new DateTime(2021, 5, 18, 11, 12, 21, 632, DateTimeKind.Local).AddTicks(4790),
                            ReminderStartDate = new DateTime(2021, 5, 18, 11, 12, 21, 632, DateTimeKind.Local).AddTicks(4055)
                        },
                        new
                        {
                            Id = 2,
                            Amount = 10L,
                            Code = "NVL2",
                            Description = "Bột gạo dùng để làm bánh",
                            IdMaterialsType = 2,
                            Max = 100L,
                            Min = 10L,
                            Name = "Cam",
                            Reminder = false,
                            ReminderEndDate = new DateTime(2021, 5, 18, 11, 12, 21, 632, DateTimeKind.Local).AddTicks(6141),
                            ReminderStartDate = new DateTime(2021, 5, 18, 11, 12, 21, 632, DateTimeKind.Local).AddTicks(6133)
                        });
                });

            modelBuilder.Entity("KhoaLuan.Data.Entities.MaterialsType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("GroupType")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .UseCollation("SQL_Latin1_General_CP1_CI_AI");

                    b.HasKey("Id");

                    b.ToTable("MaterialsTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = "LoaiNVL1",
                            GroupType = 0,
                            Name = "Bột"
                        },
                        new
                        {
                            Id = 2,
                            Code = "LoaiNVL2",
                            GroupType = 0,
                            Name = "Trái Cây"
                        });
                });

            modelBuilder.Entity("KhoaLuan.Data.Entities.OrderDetail", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .UseIdentityColumn();

                    b.Property<int>("Amount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int>("EnterAmount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int>("IdMaterials")
                        .HasColumnType("int");

                    b.Property<long>("IdOrderPlan")
                        .HasColumnType("bigint");

                    b.Property<int?>("IdSupplier")
                        .HasColumnType("int");

                    b.Property<string>("Note")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<decimal?>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("IdMaterials");

                    b.HasIndex("IdOrderPlan");

                    b.HasIndex("IdSupplier");

                    b.ToTable("OrderDetails");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Amount = 2,
                            EnterAmount = 0,
                            IdMaterials = 1,
                            IdOrderPlan = 1L,
                            Status = false,
                            Unit = "kg"
                        },
                        new
                        {
                            Id = 2L,
                            Amount = 3,
                            EnterAmount = 0,
                            IdMaterials = 2,
                            IdOrderPlan = 1L,
                            IdSupplier = 1,
                            Status = false,
                            Unit = "Trái"
                        });
                });

            modelBuilder.Entity("KhoaLuan.Data.Entities.OrderPlan", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .UseIdentityColumn();

                    b.Property<bool>("Censorship")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValue(new DateTime(2021, 5, 18, 11, 12, 21, 565, DateTimeKind.Local).AddTicks(5539));

                    b.Property<DateTime>("ExpectedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValue(new DateTime(2021, 5, 18, 11, 12, 21, 565, DateTimeKind.Local).AddTicks(5974));

                    b.Property<Guid?>("IdAuthority")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IdCreator")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IdResponsible")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Note")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<bool>("Order")
                        .HasColumnType("bit");

                    b.Property<int>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1);

                    b.HasKey("Id");

                    b.HasIndex("IdAuthority");

                    b.HasIndex("IdCreator");

                    b.HasIndex("IdResponsible");

                    b.ToTable("OrderPlans");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Censorship = true,
                            Code = "KHDH1",
                            CreatedDate = new DateTime(2021, 5, 18, 11, 12, 21, 635, DateTimeKind.Local).AddTicks(7166),
                            ExpectedDate = new DateTime(2021, 5, 18, 11, 12, 21, 635, DateTimeKind.Local).AddTicks(7899),
                            IdCreator = new Guid("0275d5a7-da4a-41c3-85ed-15e53cd1b7a0"),
                            IdResponsible = new Guid("0275d5a7-da4a-41c3-85ed-15e53cd1b7a0"),
                            Name = "Đặt hàng bột gạo và cam",
                            Order = false,
                            Status = 0
                        });
                });

            modelBuilder.Entity("KhoaLuan.Data.Entities.Pack", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .UseIdentityColumn();

                    b.Property<bool>("Default")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<int?>("IdMaterials")
                        .HasColumnType("int");

                    b.Property<int?>("IdProduct")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("PackType")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<long>("Value")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("IdMaterials");

                    b.HasIndex("IdProduct");

                    b.ToTable("Packs");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Default = true,
                            IdMaterials = 1,
                            Name = "kg",
                            PackType = 0,
                            Value = 1L
                        },
                        new
                        {
                            Id = 2L,
                            Default = false,
                            IdMaterials = 1,
                            Name = "g",
                            PackType = 0,
                            Value = 1000L
                        },
                        new
                        {
                            Id = 3L,
                            Default = true,
                            IdProduct = 1,
                            Name = "Bánh",
                            PackType = 1,
                            Value = 1L
                        });
                });

            modelBuilder.Entity("KhoaLuan.Data.Entities.ProcessPlan", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .UseIdentityColumn();

                    b.Property<bool>("Censorship")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValue(new DateTime(2021, 5, 18, 11, 12, 21, 546, DateTimeKind.Local).AddTicks(6159));

                    b.Property<DateTime>("ExpectedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValue(new DateTime(2021, 5, 18, 11, 12, 21, 546, DateTimeKind.Local).AddTicks(6581));

                    b.Property<Guid>("IdCreator")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IdResponsible")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Note")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<bool>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.HasKey("Id");

                    b.HasIndex("IdCreator");

                    b.HasIndex("IdResponsible");

                    b.ToTable("ProcessPlans");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Censorship = false,
                            Code = "KHCB1",
                            CreatedDate = new DateTime(2021, 5, 18, 11, 12, 21, 640, DateTimeKind.Local).AddTicks(8520),
                            ExpectedDate = new DateTime(2021, 5, 18, 11, 12, 21, 640, DateTimeKind.Local).AddTicks(9682),
                            IdCreator = new Guid("0275d5a7-da4a-41c3-85ed-15e53cd1b7a0"),
                            IdResponsible = new Guid("0275d5a7-da4a-41c3-85ed-15e53cd1b7a0"),
                            Name = "Chế Biến bánh cam",
                            Status = false
                        });
                });

            modelBuilder.Entity("KhoaLuan.Data.Entities.ProcessingDetail", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .UseIdentityColumn();

                    b.Property<int>("Amount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<long>("IdProcessPlan")
                        .HasColumnType("bigint");

                    b.Property<int>("IdRecipe")
                        .HasColumnType("int");

                    b.Property<string>("Note")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<bool>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("IdProcessPlan");

                    b.HasIndex("IdRecipe");

                    b.ToTable("ProcessingDetails");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Amount = 1,
                            IdProcessPlan = 1L,
                            IdRecipe = 1,
                            Status = false,
                            Unit = "Bánh"
                        });
                });

            modelBuilder.Entity("KhoaLuan.Data.Entities.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<long>("Amount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasDefaultValue(0L);

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("IdProductType")
                        .HasColumnType("int");

                    b.Property<string>("Image")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("Max")
                        .HasColumnType("bigint");

                    b.Property<long?>("Min")
                        .HasColumnType("bigint");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .UseCollation("SQL_Latin1_General_CP1_CI_AI");

                    b.Property<bool>("Reminder")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<DateTime>("ReminderEndDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValue(new DateTime(2021, 5, 18, 11, 12, 21, 587, DateTimeKind.Local).AddTicks(4875));

                    b.Property<DateTime>("ReminderStartDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValue(new DateTime(2021, 5, 18, 11, 12, 21, 587, DateTimeKind.Local).AddTicks(4234));

                    b.HasKey("Id");

                    b.HasIndex("IdProductType");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Amount = 10L,
                            Code = "SP1",
                            Description = "Bánh làm từ cam vắt",
                            IdProductType = 1,
                            Max = 10L,
                            Min = 0L,
                            Name = "Bánh Cam",
                            Reminder = false,
                            ReminderEndDate = new DateTime(2021, 5, 18, 11, 12, 21, 633, DateTimeKind.Local).AddTicks(8971),
                            ReminderStartDate = new DateTime(2021, 5, 18, 11, 12, 21, 633, DateTimeKind.Local).AddTicks(8267)
                        });
                });

            modelBuilder.Entity("KhoaLuan.Data.Entities.ProductType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("IdProductTypeGroup")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .UseCollation("SQL_Latin1_General_CP1_CI_AI");

                    b.HasKey("Id");

                    b.HasIndex("IdProductTypeGroup");

                    b.ToTable("ProductTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = "LSP1",
                            IdProductTypeGroup = 1,
                            Name = "Bánh"
                        });
                });

            modelBuilder.Entity("KhoaLuan.Data.Entities.ProductTypeGroup", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .UseCollation("SQL_Latin1_General_CP1_CI_AI");

                    b.HasKey("Id");

                    b.ToTable("ProductTypeGroups");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = "NhomLSP1",
                            Name = "Thực Phẩm"
                        });
                });

            modelBuilder.Entity("KhoaLuan.Data.Entities.Recipe", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("IdProduct")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Note")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<bool>("Prioritize")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.HasKey("Id");

                    b.HasIndex("IdProduct");

                    b.ToTable("Recipes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = "CTCB1",
                            IdProduct = 1,
                            Name = "Làm bánh Cam",
                            Prioritize = true
                        });
                });

            modelBuilder.Entity("KhoaLuan.Data.Entities.RecipeDetail", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .UseIdentityColumn();

                    b.Property<int>("Amount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int>("IdMaterials")
                        .HasColumnType("int");

                    b.Property<int>("IdRecipe")
                        .HasColumnType("int");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("IdMaterials");

                    b.HasIndex("IdRecipe");

                    b.ToTable("RecipeDetails");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Amount = 1,
                            IdMaterials = 1,
                            IdRecipe = 1,
                            Unit = "kg"
                        },
                        new
                        {
                            Id = 2L,
                            Amount = 1,
                            IdMaterials = 2,
                            IdRecipe = 1,
                            Unit = "Trái"
                        });
                });

            modelBuilder.Entity("KhoaLuan.Data.Entities.Supplier", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Email")
                        .IsUnicode(false)
                        .HasColumnType("varchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .UseCollation("SQL_Latin1_General_CP1_CI_AI");

                    b.Property<string>("Phone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Tax")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.ToTable("Suppliers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "Cần Thơ",
                            Code = "NCC1",
                            Email = "nhacungcap@gmail.com",
                            Name = "Công Ty ABO",
                            Phone = "0869696969",
                            Tax = "011"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles");

                    b.HasData(
                        new
                        {
                            UserId = new Guid("0275d5a7-da4a-41c3-85ed-15e53cd1b7a0"),
                            RoleId = new Guid("88a28f0b-99cd-4893-ab70-0189c8c7fec5")
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens");
                });

            modelBuilder.Entity("KhoaLuan.Data.Entities.Bill", b =>
                {
                    b.HasOne("KhoaLuan.Data.Entities.AppUser", "Creator")
                        .WithMany("Bills")
                        .HasForeignKey("IdCreator")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("KhoaLuan.Data.Entities.OrderPlan", "OrderPlan")
                        .WithMany("Bills")
                        .HasForeignKey("IdPlan")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("KhoaLuan.Data.Entities.Supplier", "Supplier")
                        .WithMany("Bills")
                        .HasForeignKey("IdSupplier")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Creator");

                    b.Navigation("OrderPlan");

                    b.Navigation("Supplier");
                });

            modelBuilder.Entity("KhoaLuan.Data.Entities.BillDetail", b =>
                {
                    b.HasOne("KhoaLuan.Data.Entities.Bill", "Bill")
                        .WithMany("BillDetails")
                        .HasForeignKey("IdBill")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("KhoaLuan.Data.Entities.Material", "Material")
                        .WithMany("BillDetails")
                        .HasForeignKey("IdMaterials")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Bill");

                    b.Navigation("Material");
                });

            modelBuilder.Entity("KhoaLuan.Data.Entities.Material", b =>
                {
                    b.HasOne("KhoaLuan.Data.Entities.MaterialsType", "MaterialsType")
                        .WithMany("Materials")
                        .HasForeignKey("IdMaterialsType")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MaterialsType");
                });

            modelBuilder.Entity("KhoaLuan.Data.Entities.OrderDetail", b =>
                {
                    b.HasOne("KhoaLuan.Data.Entities.Material", "Material")
                        .WithMany("OrderDetails")
                        .HasForeignKey("IdMaterials")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("KhoaLuan.Data.Entities.OrderPlan", "OrderPlan")
                        .WithMany("OrderDetails")
                        .HasForeignKey("IdOrderPlan")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("KhoaLuan.Data.Entities.Supplier", "Supplier")
                        .WithMany("OrderDetails")
                        .HasForeignKey("IdSupplier");

                    b.Navigation("Material");

                    b.Navigation("OrderPlan");

                    b.Navigation("Supplier");
                });

            modelBuilder.Entity("KhoaLuan.Data.Entities.OrderPlan", b =>
                {
                    b.HasOne("KhoaLuan.Data.Entities.AppUser", "Authority")
                        .WithMany("OrderPlanAuthority")
                        .HasForeignKey("IdAuthority");

                    b.HasOne("KhoaLuan.Data.Entities.AppUser", "Creator")
                        .WithMany("OrderPlanCreators")
                        .HasForeignKey("IdCreator")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("KhoaLuan.Data.Entities.AppUser", "Responsible")
                        .WithMany("OrderPlanResponsible")
                        .HasForeignKey("IdResponsible")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Authority");

                    b.Navigation("Creator");

                    b.Navigation("Responsible");
                });

            modelBuilder.Entity("KhoaLuan.Data.Entities.Pack", b =>
                {
                    b.HasOne("KhoaLuan.Data.Entities.Material", "Material")
                        .WithMany("Packs")
                        .HasForeignKey("IdMaterials");

                    b.HasOne("KhoaLuan.Data.Entities.Product", "Product")
                        .WithMany("Packs")
                        .HasForeignKey("IdProduct");

                    b.Navigation("Material");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("KhoaLuan.Data.Entities.ProcessPlan", b =>
                {
                    b.HasOne("KhoaLuan.Data.Entities.AppUser", "Creator")
                        .WithMany("ProcessPlanCreators")
                        .HasForeignKey("IdCreator")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("KhoaLuan.Data.Entities.AppUser", "Responsible")
                        .WithMany("ProcessPlanResponsibles")
                        .HasForeignKey("IdResponsible")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Creator");

                    b.Navigation("Responsible");
                });

            modelBuilder.Entity("KhoaLuan.Data.Entities.ProcessingDetail", b =>
                {
                    b.HasOne("KhoaLuan.Data.Entities.ProcessPlan", "ProcessPlan")
                        .WithMany("ProcessingDetails")
                        .HasForeignKey("IdProcessPlan")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("KhoaLuan.Data.Entities.Recipe", "Recipe")
                        .WithMany("ProcessingDetails")
                        .HasForeignKey("IdRecipe")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProcessPlan");

                    b.Navigation("Recipe");
                });

            modelBuilder.Entity("KhoaLuan.Data.Entities.Product", b =>
                {
                    b.HasOne("KhoaLuan.Data.Entities.ProductType", "ProductType")
                        .WithMany("Products")
                        .HasForeignKey("IdProductType")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProductType");
                });

            modelBuilder.Entity("KhoaLuan.Data.Entities.ProductType", b =>
                {
                    b.HasOne("KhoaLuan.Data.Entities.ProductTypeGroup", "ProductTypeGroup")
                        .WithMany("ProductTypes")
                        .HasForeignKey("IdProductTypeGroup")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProductTypeGroup");
                });

            modelBuilder.Entity("KhoaLuan.Data.Entities.Recipe", b =>
                {
                    b.HasOne("KhoaLuan.Data.Entities.Product", "Product")
                        .WithMany("Recipes")
                        .HasForeignKey("IdProduct")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("KhoaLuan.Data.Entities.RecipeDetail", b =>
                {
                    b.HasOne("KhoaLuan.Data.Entities.Material", "Material")
                        .WithMany("RecipeDetails")
                        .HasForeignKey("IdMaterials")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("KhoaLuan.Data.Entities.Recipe", "Recipe")
                        .WithMany("RecipeDetails")
                        .HasForeignKey("IdRecipe")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Material");

                    b.Navigation("Recipe");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.HasOne("KhoaLuan.Data.Entities.AppRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.HasOne("KhoaLuan.Data.Entities.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.HasOne("KhoaLuan.Data.Entities.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.HasOne("KhoaLuan.Data.Entities.AppRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("KhoaLuan.Data.Entities.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.HasOne("KhoaLuan.Data.Entities.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("KhoaLuan.Data.Entities.AppUser", b =>
                {
                    b.Navigation("Bills");

                    b.Navigation("OrderPlanAuthority");

                    b.Navigation("OrderPlanCreators");

                    b.Navigation("OrderPlanResponsible");

                    b.Navigation("ProcessPlanCreators");

                    b.Navigation("ProcessPlanResponsibles");
                });

            modelBuilder.Entity("KhoaLuan.Data.Entities.Bill", b =>
                {
                    b.Navigation("BillDetails");
                });

            modelBuilder.Entity("KhoaLuan.Data.Entities.Material", b =>
                {
                    b.Navigation("BillDetails");

                    b.Navigation("OrderDetails");

                    b.Navigation("Packs");

                    b.Navigation("RecipeDetails");
                });

            modelBuilder.Entity("KhoaLuan.Data.Entities.MaterialsType", b =>
                {
                    b.Navigation("Materials");
                });

            modelBuilder.Entity("KhoaLuan.Data.Entities.OrderPlan", b =>
                {
                    b.Navigation("Bills");

                    b.Navigation("OrderDetails");
                });

            modelBuilder.Entity("KhoaLuan.Data.Entities.ProcessPlan", b =>
                {
                    b.Navigation("ProcessingDetails");
                });

            modelBuilder.Entity("KhoaLuan.Data.Entities.Product", b =>
                {
                    b.Navigation("Packs");

                    b.Navigation("Recipes");
                });

            modelBuilder.Entity("KhoaLuan.Data.Entities.ProductType", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("KhoaLuan.Data.Entities.ProductTypeGroup", b =>
                {
                    b.Navigation("ProductTypes");
                });

            modelBuilder.Entity("KhoaLuan.Data.Entities.Recipe", b =>
                {
                    b.Navigation("ProcessingDetails");

                    b.Navigation("RecipeDetails");
                });

            modelBuilder.Entity("KhoaLuan.Data.Entities.Supplier", b =>
                {
                    b.Navigation("Bills");

                    b.Navigation("OrderDetails");
                });
#pragma warning restore 612, 618
        }
    }
}
